version: '3.4'

services:
  breakevenapi:
    container_name: breakevenapi
    image: ${DOCKER_REGISTRY-}breakevenapi
    build:
      context: .
      dockerfile: breakevenApi/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqldata,1433;User Id=sa;Password=senha#Segura!?;TrustServerCertificate=True; 
    depends_on:
      - sqldata


  sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=senha#Segura!?
      - ACCEPT_EULA=Y       
    volumes:
      - C:\Users\andre.tivo\source\persistency\breakevenApi:/var/opt/mssql/data
    ports:
      - "1450:1433"
